server.port :  7070

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:thea
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
